version: '3'
services:
  starburst:
    build:
      context: .
      dockerfile: Dockerfile.ddp-starburst
      args:
        - STARBURST_VERSION=${STARBURST_VERSION}
    image: ddp-starburst:latest
    container_name: ddp-starburst
    hostname: ddp-starburst.example.com
    depends_on:
      - ddp-base
    networks:
      - ddp
    environment:
    - STARBURST_VERSION
    ports:
      - "8080:8080"

networks:
  ddp:
