version: '3'
services:
  ddp-hbase:
    build:
      context: .
      dockerfile: Dockerfile.ddp-hbase
      args:
        - HBASE_VERSION=${HBASE_VERSION}
        - ATLAS_VERSION=${ATLAS_VERSION}
    image: ddp-hbase
    container_name: ddp-hbase
    hostname: ddp-hbase.example.com
    networks:
      - ddp
    ports:
      - "16000:16000"
      - "16010:16010"
      - "16020:16020"
      - "16030:16030"
    depends_on:
      ddp-hadoop:
        condition: service_healthy
      ddp-zookeeper:
        condition: service_started
      ddp-kafka:
        condition: service_started
    environment:
      - HBASE_VERSION
      - ATLAS_VERSION

networks:
  ddp:
