version: '3'
services:
  ddp-atlas:
    build:
      context: .
      dockerfile: Dockerfile.ddp-atlas
      args:
        - ATLAS_VERSION=${ATLAS_VERSION}
    image: ddp-atlas:latest
    container_name: ddp-atlas
    hostname: ddp-atlas.example.com
    networks:
      - ddp
    volumes:
      - ./data:/home/atlas/data
    ports:
      - "21000:21000"
    depends_on:
      ddp-hbase:
        condition: service_started
      ddp-kafka:
        condition: service_started
      ddp-solr:
        condition: service_started
      ddp-zookeeper:
        condition: service_started
    environment:
      - ATLAS_VERSION
    command:
      - /home/atlas/scripts/atlas.sh

networks:
  ddp:
