version: '3'
services:
  ddp-starburst:
    build:
      context: .
      dockerfile: Dockerfile.ddp-starburst
      args:
        - STARBURST_VERSION=${STARBURST_VERSION}
    image: ddp-starburst:latest
    container_name: ddp-starburst
    hostname: ddp-starburst.example.com
    restart: always
    depends_on:
      - ddp-base
    networks:
      - ddp
    environment:
    - STARBURST_VERSION
    ports:
      - "443:443"
    depends_on:
      ddp-kafka:
        condition: service_started
      ddp-hive:
        condition: service_started

networks:
  ddp:
