version: '3'
services:
  ddp-kafka:
    build:
      context: .
      dockerfile: Dockerfile.ddp-kafka
      args:
        - KAFKA_VERSION=${KAFKA_VERSION}
    image: ddp-kafka
    container_name: ddp-kafka
    hostname: ddp-kafka.example.com
    networks:
      - ddp
    ports:
      - "9092:9092"
    depends_on:
      ddp-zookeeper:
        condition: service_started
    environment:
      - KAFKA_VERSION

networks:
  ddp: