version: '3'
services:
  starburst:
    build:
      context: .
      dockerfile: Dockerfile.ddp-starburst
      args:
        - STARBURST_VERSION=${STARBURST_VERSION}
    image: ddp-starburst:latest
    container_name: ddp-starburst
    hostname: ddp-starburst.example.com
    restart: always
    depends_on:
      - ddp-base
    networks:
      - ddp
    environment:
    - STARBURST_VERSION
    ports:
      - "443:443"

  ddp-postgres:
    build:
        context: .
        dockerfile: Dockerfile.ddp-postgres
    image: ddp-postgres
    container_name: ddp-postgres
    hostname: ddp-postgres.example.com
    networks:
        - ddp
    ports:
      - "5432:5432"

networks:
  ddp:
