version: '3'
services:
  ddp-hive:
    build:
      context: .
      dockerfile: Dockerfile.ddp-hive
      args:
        - HIVE_HADOOP_VERSION=${HIVE_HADOOP_VERSION}
        - HIVE_VERSION=${HIVE_VERSION}
        - ATLAS_VERSION=${ATLAS_VERSION}
    image: ddp-hive
    container_name: ddp-hive
    hostname: ddp-hive.example.com
    networks:
      - ddp
    ports:
      - "10000:10000"
    depends_on:
      ddp-postgres:
        condition: service_started
      ddp-hadoop:
        condition: service_healthy
      ddp-zookeeper:
        condition: service_started
      ddp-kafka:
        condition: service_started
    environment:
      - HIVE_HADOOP_VERSION
      - HIVE_VERSION
      - ATLAS_VERSION

networks:
  ddp:
