version: '3'
services:
  ddp-base:
    build:
      context: .
      dockerfile: Dockerfile.ddp-base
    image: ddp-base
    container_name: ddp-base
    networks:
      - ddp
    environment:
      - RANGER_VERSION
      - ATLAS_VERSION
      - STARBUST_VERSION

networks:
  ddp:
