version: '3'
services:
  ddp-hadoop:
    build:
      context: .
      dockerfile: Dockerfile.ddp-hadoop
      args:
        - HADOOP_VERSION=${HADOOP_VERSION}
    image: ddp-hadoop
    container_name: ddp-hadoop
    hostname: ddp-hadoop.example.com
    networks:
      - ddp
    ports:
      - "9000:9000"
      - "8088:8088"
      - "9870:9870"
    depends_on:
      - ddp-base
    healthcheck:
      test: "hdfs dfs -ls /"
      interval: 1m30s
      timeout: 10s
      retries: 30
      start_period: 40s
    environment:
      - HADOOP_VERSION

networks:
  ddp: