version: '3'
services:
  ddp-postgres:
    build:
        context: .
        dockerfile: Dockerfile.ddp-postgres
    image: ddp-postgres
    container_name: ddp-postgres
    hostname: ddp-postgres.example.com
    networks:
        - ddp
    ports:
      - "5432:5432"

networks:
  ddp:
